# Generated by Django 3.0.5 on 2021-05-01 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.PositiveSmallIntegerField(
                null=True, validators=[
                    django.core.validators.MinValueValidator(
                        1, 'Рейтинг не может быть ниже 1'), django.core.validators.MaxValueValidator(
                        10, 'Рейтинг не может быть выше 10')], verbose_name='Рейтинг'),
        ),
    ]
